{% set name = "Flask-JWT-Extended" %}
{% set version = "3.25.0" %}
{% set sha256 = "b2e4dba91661e4697b30269106386c2b29e416a00d9ff66b26c462edddc10078" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python >=2.7
    - pip
  run:
    - flask >=1.0,<2.0
    - pyjwt >=1.6.4,<2.0
    - python >=2.7
    - six
    - werkzeug >=0.14

test:
  imports:
    - flask_jwt_extended

about:
  home: https://github.com/vimalloc/flask-jwt-extended
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Flask JWT extension

  description: |
    A Flask JWT extension that supports refresh tokens, blacklisting/revoking tokens,
    and token freshness (for accessing critical views)

extra:
  recipe-maintainers:
    - lvoliveira
    - nicoddemus
    - igortg
    - synapticarbors
