{% set name = "Flask-JWT-Extended" %}
{% set version = "4.2.3" %}
{% set sha256 = "22b8ffa7587d50aaf65f3009f1d55ef7287da8260eaf4655a5837e33479216c3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python >=3.6
    - pip
  run:
    - flask >=1.0,<3.0
    - pyjwt >=2.0,<3.0
    - python >=3.6
    - werkzeug >=0.14

test:
  imports:
    - flask_jwt_extended

about:
  home: https://github.com/vimalloc/flask-jwt-extended
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Flask JWT extension

  description: |
    A Flask JWT extension that supports refresh tokens, blacklisting/revoking tokens,
    and token freshness (for accessing critical views)

extra:
  recipe-maintainers:
    - lvoliveira
    - nicoddemus
    - igortg
    - synapticarbors
