context:
  version: "4.7.3"

package:
  name: flask-jwt-extended
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/flask-jwt-extended/flask_jwt_extended-${{ version }}.tar.gz
  sha256: a8318a3d983d1f360724b901889f1947ffee418e2a3950b48e99c70923b6615e

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - flask >=2.0,<4.0
    - pyjwt >=2.0,<3.0
    - python >=${{ python_min }}
    - werkzeug >=0.14

tests:
  - python:
      imports:
        - flask_jwt_extended
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: A Flask JWT extension
  description: |
    A Flask JWT extension that supports refresh tokens, blacklisting/revoking tokens,
    and token freshness (for accessing critical views)
  homepage: https://github.com/vimalloc/flask-jwt-extended

extra:
  recipe-maintainers:
    - lvoliveira
    - nicoddemus
    - synapticarbors
